export const generateEnglish = [
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam maiores delectus amet, architecto accusamus quidem modi laudantium repellat at nesciunt? Provident, sed cupiditate ipsam repellendus deleniti tempore maiores voluptatibus fugiat.",
    "veritatis sed, eaque nobis ducimus? Voluptate corporis facere laboriosam commodi aspernatur iste, odio, quisquam saepe ea alias voluptatum maiores doloribus molestias tenetur. Et neque veniam aliquid inventore ipsam suscipit ad eos hic doloremque!",
    "consequatur beatae error officiis labore incidunt. Rem dignissimos quisquam odit numquam aliquam! Sequi architecto distinctio earum obcaecati amet, odio autem quos in velit ex est vitae, debitis ducimus repudiandae tempora? Culpa dolorum accusantium ipsa dolor nemo debitis,",
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, doloribus ullam perferendis totam deserunt sed natus magnam consequatur beatae error officiis labore incidunt. Rem dignissimos quisquam odit numquam aliquam! Sequi architecto distinctio",
    "en parkes ipsum dolor, sit amet consectetur adipisicing elit. At accusamus quasi voluptas similique. Porro at fuga distinctio, sapiente cupiditate explicabo, quae consectetur consequatur mollitia, quibusdam voluptas vero placeat fugit error?",
    "nobis eum sed impedit sapiente tenetur ea quisquam, a pariatur aspernatur adipisci aliquam? Eos a odio laudantium natus, nemo error unde ullam iste repudiandae fuga atque eveniet cumque magnam. Dicta nesciunt provident dolorum repellat consequatur. Consequuntur autem maiores distinctio. Neque consequuntur excepturi quas, eum tempore enim hic.",
    "fake word ipsum dolor sit amet consectetur, adipisicing elit. In, nobis quam? Animi excepturi, itaque cum vitae repudiandae nobis omnis dolor, illum nisi fugiat facilis doloremque. Ducimus minima error sed recusandae ex voluptatum eligendi deserunt omnis similique reprehenderit, odit accusantium in. Temporibus similique beatae maxime aperiam, quas labore odio ad officia necessitatibus aut quasi ",
];
export const generatePersian = [
    "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز",
    " و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه",
    " راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد",
    " و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    "مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    "طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا ",
];
